import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import "./globals.css";
import { ThemesProvider } from "@/components/shared/theme-provider";
import { AppSidebar } from "@/components/sidebar/sidebar";
import { SidebarProvider } from "@/components/ui/sidebar";

export const metadata: Metadata = {
  title: "Huntear - Job Application Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      suppressHydrationWarning>
      <body className={`${GeistSans.className}`}>
        <SidebarProvider>
          <ThemesProvider
            attribute='class'
            defaultTheme='system'
            enableSystem>
            <AppSidebar />
            <main className='w-full'>{children}</main>
          </ThemesProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
